### ISSUE TITLE
Gotham 13.2 sqlite INSTR error

### ISSUE THREAD

**Issue by Ilia** [bstrdsmkr/1Channel#187]
With latest master 2.5.60, i am getting this on my mac running 13.2

0:37:34 T:4589260800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such function: INSTR
                                            Traceback (most recent call last):
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/default.py", line 2008, in <module>
                                                sys.exit(main())
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/default.py", line 2005, in main
                                                pw_dispatcher.dispatch(mode, _1CH.queries)
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/pw_dispatcher.py", line 81, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/default.py", line 621, in AddonMenu
                                                fix_urls()
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/default.py", line 615, in fix_urls
                                                db_connection.execute_sql("UPDATE %s SET url=REPLACE(url,'-online-free','') WHERE INSTR(url,'-online-free')>0" % (table))
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/db_utils.py", line 288, in execute_sql
                                                return self.__execute(sql)
                                              File "/Users/ilia/Library/Application Support/XBMC/addons/1Channel/db_utils.py", line 452, in __execute
                                                cur.execute(sql, params)
                                            OperationalError: no such function: INSTR

**Comment by tknorris** [comment]
This is my fault. I forgot to push my latest fix for this to bstdsmrk's repo. I'll do that now. IT uses substr instead of instr.

**Comment by tknorris** [comment]
Should be fixed.
