### ISSUE TITLE
Error upon finishing watch

### ISSUE THREAD

**Issue by thwaller** [bstrdsmkr/1Channel#202]
I am receiving an error notification and the following in the log file after completing watching a show and getting the rating dialog from Trakt. The show is being marked as watched both in Kodi and Trakt and the rating is being posted to Trakt, but not to Kodi. This is from a 1Channel library item being played with the 1Channel addon. I am on Kodi v16 with Trakt 3.1.3 (patched one) and 1Channel 2.5.68.

05:07:44 T:2735659840  NOTICE: 1Channel: Calling |change_watched| for mode |ChangeWatched| with pos args |['episode', 'Faking It (2014)', '/tv-2745792-Faking-It-2014/season-1-episode-1', True]| and kwargs |{'season': '1', 'episode': '1', 'dbid': '6128', 'imdbnum': None}|
05:07:45 T:2735659840  NOTICE: PrimeWire: Marking episode .strm as watched: {"id":1,"jsonrpc":"2.0","result":"OK"}
05:07:47 T:2735659840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            Traceback (most recent call last):
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/default.py", line 1939, in <module>
                                                sys.exit(main())
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/default.py", line 1936, in main
                                                pw_dispatcher.dispatch(mode, _1CH.queries)
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/pw_dispatcher.py", line 81, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/default.py", line 489, in change_watched
                                                change_watched_website(primewire_url, whattodo, refresh=False)
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/default.py", line 496, in change_watched_website
                                                pw_scraper.change_watched(primewire_url, "watched", action)
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/pw_scraper.py", line 462, in change_watched
                                                self.__get_url(change_url, login=True)
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/pw_scraper.py", line 499, in __get_url
                                                if self.__login(self.base_url):
                                              File "/home/brian/.kodi/addons/plugin.video.1channel/pw_scraper.py", line 607, in __login
                                                html = net.http_POST(url, headers=headers, form_data=form_data).content
                                              File "/home/brian/.kodi/addons/script.module.addon.common/lib/addon/common/net.py", line 212, in http_POST
                                                compression=compression)
                                              File "/home/brian/.kodi/addons/script.module.addon.common/lib/addon/common/net.py", line 270, in _fetch
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 442, in error
                                                result = self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
                                                return self.parent.open(new, timeout=req.timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
                                                return self.do_open(httplib.HTTPSConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            -->End of Python script error report<--
05:07:54 T:2827979584  NOTICE: service.watchedlist: watch_user_changes: episode "Faking It (2014) S01E01" changed playcount {0 -> 1} lastplayed {"" -> "2016-03-06 05:07:45"}. episodeid=6128
05:07:54 T:2827979584  NOTICE: service.watchedlist: wl_update_episode: new entry for wl database: "Faking It (2014) S01E01", lastChange="2016-03-06 05:07:54", lastPlayed="2016-03-06 05:07:45", playCount=1
05:08:29 T:2735659840 WARNING: Attempt to use invalid handle -1

**Comment by tknorris** [comment]
try manually changing the domain you are using in 1CH to be "https://www.primewire.ag". They disallowed logins on non-https addresses a while back.

**Comment by thwaller** [comment]
Changing to what you suggested causes a cannot connect error while trying to open a show in 1Channel.

**Comment by tknorris** [comment]
I'll give it a try later today and see if it's working here.

**Comment by thwaller** [comment]
I will play with it as well. I can also look at the .is, .org as well as the .ag. When I do not use https, I can connect and get shows. Using https, it fails to connect. I will try disabling website integration and see if I still get that error.

**Comment by tknorris** [comment]
With website integration turned off you shouldn't get it because it doesn't update your primewire watched status.

**Comment by thwaller** [comment]
that is no good then. same error on all the .is, .org and .ag. I will wait on your testing.

**Comment by tknorris** [comment]
I just tested and it worked fine. Do you know what version of python you are running? It won't work on any version prior to 2.7.10

**Comment by thwaller** [comment]
2.7 and 3.4 both show installed.
with http, all works but I get the error above.
with https, nothing works, cannot connect to url

**Comment by tknorris** [comment]
2.7 what though?

**Comment by thwaller** [comment]
2.7.6

**Comment by thwaller** [comment]
what happens is i change to https, have integration enabled and select 1channel to run. i select a show and it fails before finding sources.

**Comment by tknorris** [comment]
Upgrade to 2.7.10 or later. No version of Python prior to that will work
with website integration any longer.

**Comment by thwaller** [comment]
will that work on trusty, 14.04?

**Comment by thwaller** [comment]
closing as the issue has been explained.

**Comment by tknorris** [comment]
Yeah, there is a ppa to upgrade Trusty's python to the latest 2.7

**Comment by thwaller** [comment]
huh, ok. i will look for it. the one i saw is for wily. thanks.

**Comment by tknorris** [comment]
https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7

**Comment by thwaller** [comment]
Cheers!
